### ISSUE TITLE
Error log from updating version 01. to 0.3

### ISSUE THREAD

**Issue by MilesNaismith1** [JekiTheMonkey/KPS#16]
[JKPS_errlog.txt](https://github.com/JekiTheMonkey/JKPS/files/8374820/JKPS_errlog.txt)

**Comment by Tonetfal** [comment]
It is ok having such error log on updating from an older version to a new one. As you can understand from the log, v0.3 can't read some parameters from v0.1 config just because the old config doesn't contain new features, although they'll be imported in your config as soon as you run the program successfully, that's it.
